#!/bin/sh
### BEGIN INIT INFO
# Provides:          simplenet-ovs-agent
# Required-Start:    $network $local_fs
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simpletnet OVS agent
# Description:       Simpletnet OVS agent
### END INIT INFO

# Author: Luiz Ozaki <luiz.ozaki@locaweb.com.br>
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="Simpletnet OVS agent"
NAME=simplenet-ovs-agent

DAEMON=sn-ovs-agent
DAEMON_BIN=/usr/sbin/sn-ovs-agent
DAEMON_PIDFILE=/var/run/simplenet-ovs-agent.pid
SCRIPTNAME=/etc/init.d/$NAME

# Exit if the package is not installed
[ -x "$DAEMON_BIN" ] || exit 0

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

. /etc/rc.d/init.d/functions

RETVAL=0

create_xconsole() {
    XCONSOLE=/dev/xconsole
    if [ "$(uname -s)" = "GNU/kFreeBSD" ]; then
        XCONSOLE=/var/run/xconsole
        ln -sf $XCONSOLE /dev/xconsole
    fi
    if [ ! -e $XCONSOLE ]; then
        mknod -m 640 $XCONSOLE p
        chown root:adm $XCONSOLE
        [ -x /sbin/restorecon ] && /sbin/restorecon $XCONSOLE
    fi
}

rh_status() {
    status -p $DAEMON_PIDFILE $DAEMON
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}

start() {
    rh_status_q && return 0
    echo -n $"Starting $DESC" "$DAEMON"
    create_xconsole
    daemon --pidfile=$DAEMON_PIDFILE $DAEMON -a start
    RETVAL=$?

    echo
    return $RETVAL
}

stop() {
    rh_status_q && return 0
    echo -n $"Stopping $DESC" "$DAEMON"

    daemon --pidfile=$DAEMON_PIDFILE $DAEMON -a stop
    RETVAL=$?

    echo
    return $RETVAL
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  status)
    rh_status
    ;;
  *)
    echo "Usage: $SCRIPTNAME {start|stop|restart|status}" >&2
    exit 3
    ;;
esac

exit $RETVAL
